// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp1UIqpP4Elf4ez3RS9hnxcih--fJmkt0',
    appId: '1:458875237618:web:df2adba717f968e1798c6b',
    messagingSenderId: '458875237618',
    projectId: 'reddit-clone-745ef',
    authDomain: 'reddit-clone-745ef.firebaseapp.com',
    storageBucket: 'reddit-clone-745ef.appspot.com',
    measurementId: 'G-CP982RFTKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSWZvCjD_MbyqNL-VI7peanBfTp0Nlt0k',
    appId: '1:458875237618:android:e791af472f99e788798c6b',
    messagingSenderId: '458875237618',
    projectId: 'reddit-clone-745ef',
    storageBucket: 'reddit-clone-745ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyLC9k18MTT6zcMH4g_mygYTV8W268QOk',
    appId: '1:458875237618:ios:fa5ad78ff5c3e24d798c6b',
    messagingSenderId: '458875237618',
    projectId: 'reddit-clone-745ef',
    storageBucket: 'reddit-clone-745ef.appspot.com',
    iosClientId: '458875237618-jik3383g1p92v9uf4jfjot9q8j9agikp.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
